### PR TITLE
Basic anyhow integration

### LINKED ISSUE #162: anyhow integration
[`anyhow`](https://github.com/dtolnay/anyhow) is a great, small and clean `failure` create replacement that was released very recently, would be great to have a sentry integration for it. 
Probably can use the `failure` one as a base.

We are currently testing to transition from `failure` to `anyhow` to have a simpler library that implements `std::error::Error`

### PR DESCRIPTION
**Pull request by repi**
This adds an optional integration for the [`anyhow`](https://crates.io/crates/anyhow) error crate that can be enabled with the `with_anyhow` feature.

It works very similar to the `failure` crate but does not here support backtraces, as `anyhow` only supports backtraces on nightly. One could implement support for nightly-only backtraces but we don't have a need for that so didn't do it in this PR.

Fix #162

### CODE REVIEW

**Comment by repi** [comment]
Any feedback on the change? Something you would be able to integrate?

**Comment by quininer** [comment]
I understand that sentry has recently changed in open source, is sentry no longer accepting community contributions?

**Comment by repi** [comment]
@quininer only the licensing for the server components changed: https://twitter.com/mitsuhiko/status/1192188542988038146. and  sentry-rust is a client-side only library

**Comment by siedentop** [comment]
@repi  could you please update the branch with the base branch?

**Comment by repi** [comment]
The maintainers of this repo have not given any feedback about this in 3 months, I will not do any further work on this. We have our own fork of sentry-rust that we use for now with this and additional changes.

**Comment by Tomcc** [comment]
As of a few hours ago [`failure` has been deprecated](https://github.com/rust-lang-nursery/failure/pull/347) in favor of `anyhow`, so this issue probably became a lot more important.
`sentry` is the only crate preventing me from switching off `failure`... I could always write my own integration, but it'd be nice to give this PR some more love instead :)

**Comment by Swatinem** [comment]
I’m making good progress with the internals, and will try to get to all the open PRs in the next few weeks :-)

**Comment by Swatinem** [comment]
closing, as this was added in #212

**Pull request closed without merging**
