### PR TITLE
sentry-core: add public getters for TransactionContext

### PR DESCRIPTION
**Pull request by tommilligan**
Split from #512, to enable support for `traces_sampler` inspecting first class properties of `TransactionContext`.

This was split as we though the addition of `CustomTransactionContext` may require further discussion, while these changes should be uncontroversial.

ref: https://github.com/getsentry/sentry-rust/pull/512#issuecomment-1304747662

### CODE REVIEW

**Review by loewenheim — APPROVED** [review]

**Comment by Turbo87** [comment]
@loewenheim is there anything blocking from this getting merged and released? not sure about the process to move this forward :)

**Comment by loewenheim** [comment]
Not at all, I think master just needs to be merged into it :)

**Comment by Turbo87** [comment]
@loewenheim can we help with the release in some way? :)

**Comment by loewenheim** [comment]
Just started the ball rolling :)

**Pull request merged**
