### PR TITLE
Upgrade reqwest to 0.10.0

### PR DESCRIPTION
**Pull request by repi**
This can't be merged yet as it contains a git patch to use latest reqwest for rustls support, but will upgrade this to next reqwest official 0.10.0 release later.

### CODE REVIEW

**Comment by jeromegn** [comment]
There's now a stable 0.10.0 reqwest release.

**Comment by repi** [comment]
Upgrade to the released 0.10.0 version of reqwest now

**Comment by glebpom** [comment]
Why is it rustls? Can we enable it through feature?

**Comment by repi** [comment]
rustls or openssl could probably be a feature yes, though we only use rustls.

Also Rust minimum version has to be bumped to at least 1.36 it looks like.

I'm wary of doing those changes here though as this repo doesn't really seem to be maintained anymore and the devs have not been responsive. So we have our own fork that we maintain and may slim down to just the minimal functionality that we use.

Think for example http access should be abstracted to a trait here for the app to implement instead of using really large dependency.

**Comment by glebpom** [comment]
@repi thanks for your comments

**Comment by bbigras** [comment]
> we have our own fork that we maintain and may slim down to just the minimal functionality that we use.

@repi Any plans to publish and maintain that fork?

**Comment by repi** [comment]
@bbigras we haven't done a stripped down version yet, right now we just use the fork that this PR points to (which is not published on crates.io). 

But think `sentry-rust` has way too many dependencies, features and logic in it that has caused multiple maintenance and upgrade challenges so starting from scratch with a very minimal client would be ideal.

**Comment by kornelski** [comment]
If you rebase on master, it should pass CI now.

**Comment by mitsuhiko** [comment]
@repi i agree it's too large. I want to see what we can do here.

**Comment by kornelski** [comment]
@repi you need to bump Rust to 1.37 in travis.yml, because newer `bytes` dependency requires it.

**Comment by kornelski** [comment]
See #179 - it also will complain about a clippy lint and rustfmt

**Comment by kornelski** [comment]
@repi See #179 - CI complains about a clippy lint and rustfmt

**Comment by jan-auer** [comment]
This is incorporated into https://github.com/getsentry/sentry-rust/pull/183, thanks for your efforts. I'm closing this here. 

Note that the only difference is that we're not enabling rustls by default.

**Pull request closed without merging**
