### PR TITLE
Updated `failure` integration for new backtrace display

### LINKED ISSUE #105: Stacktrace parsing in the `failure` integration is outdated
Line display seems to have changed in the failure.backtrace formatting (or at least doesnt't work in my case with ACTIX integration).
- [ ] It should be updated. (I'm working on it, PR incoming.)

It would have been nice if `Backtrace` provided methods to access internal representation without having to go Backtrace->String->Regex->Sentry... ^^

In order to ensure this will not happen again :

- [ ] Shouldn't the `api::protocol::Stacktrace::from_frames_reversed` call not silent-fail by returning an option when the vector is empty ? (asking for advice)

- [ ] A test should be added to ensure any similar format change would be detected.

### PR DESCRIPTION
**Pull request by Ten0**
FIX #105 (.1)

### CODE REVIEW

**Comment by Ten0** [comment]
Note that the build fails are unrelated. (Dependencies failing to build on Rust 1.28 and Zeus config problems)

**Comment by mitsuhiko** [comment]
Thanks!

**Comment by mitsuhiko** [comment]
Should already have been fixed.

**Comment by mitsuhiko** [comment]
Cannot reproduce. Says 0.1.5 was released yesterday.

**Comment by mitsuhiko** [comment]
Sorry I thought this was about a different repo. Yes we will release a new version of this soon.

**Comment by 0xcaff** [comment]
@Ten0 Did you ever release this Rocket sentry thing? I couldn't find one when I looked.

**Comment by Ten0** [comment]
> @Ten0 Did you ever release this Rocket sentry thing? I couldn't find one when I looked.

@0xcaff Yes! https://crates.io/crates/sentry_rocket
I just tried updating the doc and publishing it but it seems to not compile anymore due to some weird stuff with rand. Considering this is nightly, I don't think it's linked. Anyway, you can find the source code and examples on the git repository if you manage to make it work :)

**Pull request merged**
