### PR TITLE
feat: add feature for using surf with the h1-client and rustls

### PR DESCRIPTION
**Pull request by misuzu**
This feature enables usage of `surf` http backend with `rustls`.

### CODE REVIEW

**Review by flub — APPROVED** [review]

**Review by flub — CHANGES_REQUESTED** [review]
hum, seems like CI says this isn't so simple.  Could you fix this?

**Comment by flub** [comment]
could be because of `--all-features` use by CI, so this may need more CI tweaks to make this work.

**Comment by MarijnS95** [comment]
It should now be possible to add this directly under the `rustls` feature when https://github.com/getsentry/sentry-rust/pull/454 lands :tada:

**Comment by MarijnS95** [comment]
@misuzu I meant for you to rebase and add it in this PR, as I did not enable the feature in #454 :wink:

**Comment by misuzu** [comment]
> @misuzu I meant for you to rebase and add it in this PR, as I did not enable the feature in #454 wink

AFAIU surf is still needs to be updated and there was no releases since last year. I'll submit new pull-request after next release of surf.

**Comment by MarijnS95** [comment]
Feel free to just reuse PRs, makes it easier on the deep-linking.

**Pull request closed without merging**
