### PR TITLE
Calculate debug ID on linux

### PR DESCRIPTION
**Pull request by Diggsey**
Uses goblin to load the build ID from all shared libraries found by `findshlibs`. (Still testing)

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Might make sense to disable default features and only use the minimum set necessary. goblin is quite large.

**Comment by mitsuhiko** [comment]
@Diggsey thanks for this fix. I quickly looked at the support issue and from what I can tell the `debug_meta` we're producing in the rust library is incorrect. It reports the executable at `0x0` instead of `0x40000` or where it should be. I think we just report the wrong segment here.

**Comment by mitsuhiko** [comment]
@Diggsey i tried your (pre force push) patch against sentry.io now on a small app on ubuntu and I got it symbolicated just fine.

Here is what it looks like for me (panic example): https://sentry.io/share/issue/60464ee6ae224ed2a819f5b19bfc9bb7/

Can you share more about your setup?

**Comment by mitsuhiko** [comment]
Closing for #114

**Comment by Diggsey** [comment]
@mitsuhiko ah great, not sure what happened with that last force push, definitely didn't mean to do that...

The most likely cause of the difference is that I'm compiling for musl. I suspect on musl one of the segments reports address zero, and then it picks that as the base address, when it's not. I will investigate some more.

**Comment by Diggsey** [comment]
Yes, these are the segments returned by `findshlibs`:

```
vm bias: Bias(0)
name: "LOAD"
stated: Svma(0x400000)
actual: Avma(0x400000)
name: "LOAD"
stated: Svma(0xf2c5e0)
actual: Avma(0xf2c5e0)
name: "NOTE"
stated: Svma(0x4001c8)
actual: Avma(0x4001c8)
name: "TLS"
stated: Svma(0xf2c5e0)
actual: Avma(0xf2c5e0)
name: "GNU_EH_FRAME"
stated: Svma(0xaa60e0)
actual: Avma(0xaa60e0)
name: "GNU_STACK"
stated: Svma(0x0)
actual: Avma(0x0)
name: "GNU_RELRO"
stated: Svma(0xf2c5e0)
actual: Avma(0xf2c5e0)
```

The presence of `GNU_STACK` is confusing things.

This is the sentry code:
```rust
            for seg in shlib.segments() {
                let svma: u64 = seg.stated_virtual_memory_address().0 as u64;
                let avma: u64 = seg.actual_virtual_memory_address(shlib).0 as u64;
                if lowest_addr > avma {
                    lowest_addr = avma;
                }
                if highest_addr < avma {
                    highest_addr = avma;
                }
                if lowest_vmaddr > svma {
                    lowest_vmaddr = svma;
                }
            }
```

This seems a little odd to me... Is the "vm" address here definitely supposed to be the *stated* address rather than the actual address?

I'm not sure what the correct way to find the "true" base address is. Should it only be looking for "LOAD" segments? Or maybe it should just pick the first segment?

**Comment by mitsuhiko** [comment]
We currently only care about the image_addr in the debug image section except for output in apple crash reports. I guess the correct thing to do would be to only look at load sections but they might have to be adjusted for all platforms that findshlibs supports. I feel like there might be API missing in findshlibs to support this well.

**Comment by jan-auer** [comment]
The second load section will also already lead to wrong offsets. Interestingly, I noticed that only the first eine is mapped with the executable bit set. So maybe we would need to filter for both the name and bits when computing addresses. 

And yes, the actual address is correct.

**Comment by jan-auer** [comment]
Thinking about this a little. In Sentry (symbolic, actually) we also only look at the address of the first PT_LOAD program header. This is also what Breakpad does iirc. This leads me to believe that this should be reasonably safe.

**Comment by mitsuhiko** [comment]
I think we should send a PR against findshlibs to add an `is_code` accessor to the segment which returns `true` for `PT_LOAD`/`LC_SEGMENT`/`LC_SEGMENT64` and then use the first one.

**Comment by Diggsey** [comment]
@mitsuhiko on osx, `findshlibs` only returns segments of type `LC_SEGMENT[64]` in the first place.

**Comment by mitsuhiko** [comment]
Still needs to check for segment name `__TEXT` i think.

**Comment by Diggsey** [comment]
I can confirm this fixes the problem.

**Comment by mitsuhiko** [comment]
@Diggsey pushed up this: https://github.com/getsentry/sentry-rust/pull/117

**Comment by Diggsey** [comment]
Cool, tested again with your branch and it's all working. Feel free to close the support ticket. 👍 

Given that sentry can be given access to github repos, and can correlate them with releases, it would be nice if it matched up stack frames with the corresponding code snippets pulled in from github 😛

**Comment by mitsuhiko** [comment]
We were thinking about the github thing but it's harder in practice than it appears (because not everything is contained in that repo or in the structure one wants). We were talking about adding source archives that already map to the file locations that are also referenced in the debug files.

**Pull request closed without merging**
