### PR TITLE
sentry-core: make TransactionContext.trace_id readable

### PR DESCRIPTION
**Pull request by tommilligan**
I would like to add the Sentry trace_id to our internal logs to be able to correlate it with the sentry transaction. Currently this isn't publicly accessible anywhere.

### CODE REVIEW

**Review by kamilogorek — APPROVED** [review]
This is already possible in JS SDK, so I don't see a reason why it shouldn't be here.

**Comment by tommilligan** [comment]
> This is already possible in JS SDK, so I don't see a reason why it shouldn't be here.

Agreed, thanks. I already access `trace_id` as publicly accessible in the Python SDK, so figured it would be fine to have here too.

Note that this PR only exposes it on the `TransactionContext`, I think it could be exposed on `Transaction` as well, but that looked like a bit more effort/design required.

**Comment by kamilogorek** [comment]
> Note that this PR only exposes it on the TransactionContext, I think it could be exposed on Transaction as well, but that looked like a bit more effort/design required.

cc @Swatinem

**Comment by Swatinem** [comment]
IMO its a good idea to also expose that on the `Transaction`, `Span` and `TransactionOrSpan` types.

**Comment by tommilligan** [comment]
> IMO its a good idea to also expose that on the `Transaction`, `Span` and `TransactionOrSpan` types.

I'm happy to pick this up as a subsequent PR. The simplest option would be to expose the `TraceContext` using a getter, is it acceptable to expose the inner protocol structs in that way? https://github.com/getsentry/sentry-rust/blob/5013eb1fdca505ef9c7c28266afcf847da7c17b3/sentry-types/src/protocol/v7.rs#L1439

Alternatively I could look at exposing the fields individually, which would be quite boilerplate heavy.

**Comment by tommilligan** [comment]
Opened a separate PR for exposing on the `Transaction`/`Span` types here: https://github.com/getsentry/sentry-rust/pull/534

**Review by Swatinem — APPROVED** [review]

**Comment by tommilligan** [comment]
Is there a scheduled release cadence for the sentry family of crates? Would like to know when a release with this in is likely to be cut

**Comment by Swatinem** [comment]
We don’t have a fixed cadence, rather adhoc. I triggered the automated release which needs to be approved and should be out shortly: https://github.com/getsentry/publish/issues/1766

**Comment by tommilligan** [comment]
Amazing, thank you

**Pull request merged**
